"""add password column to users table

Revision ID: 069bdffdc574
Revises: 5639585da492
Create Date: 2024-07-28 10:37:27.267048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069bdffdc574'
down_revision = '5639585da492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
