"""Recreate database schema

Revision ID: 1dec4a61c089
Revises: 8566df2b164a
Create Date: 2024-08-01 19:19:24.389673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dec4a61c089'
down_revision = '8566df2b164a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_destination_association', schema=None) as batch_op:
        batch_op.create_index('ix_user_destination', ['user_id', 'destination_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_destination_association', schema=None) as batch_op:
        batch_op.drop_index('ix_user_destination')

    # ### end Alembic commands ###
