"""add activities table

Revision ID: 3376f200c2c7
Revises: 6debfc7aa61a
Create Date: 2024-07-27 15:15:44.718582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3376f200c2c7'
down_revision = '6debfc7aa61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_activities_destination_id_destinations')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_activities_trip_id_trips')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
