"""add constraints to username

Revision ID: 4bb73bd04e1c
Revises: 3376f200c2c7
Create Date: 2024-07-27 20:09:05.986742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb73bd04e1c'
down_revision = '3376f200c2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favoriteDestinations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('favoriteDestinations', schema=None) as batch_op:
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
