"""create users table

Revision ID: 51789c7ee9d2
Revises: 26b307da64c3
Create Date: 2024-07-25 17:22:20.783002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51789c7ee9d2'
down_revision = '26b307da64c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
