"""empty message

Revision ID: 5581765df422
Revises: da102e2ad05e
Create Date: 2024-08-11 12:19:38.437117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5581765df422'
down_revision = 'da102e2ad05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_activities_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_trip_id_trips'), type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###
