"""create join table FavoriteDestination

Revision ID: 6debfc7aa61a
Revises: ef438735f66b
Create Date: 2024-07-27 13:34:02.242470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6debfc7aa61a'
down_revision = 'ef438735f66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoriteDestinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_favoriteDestinations_destination_id_destinations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favoriteDestinations_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoriteDestinations')
    # ### end Alembic commands ###
