"""empty message

Revision ID: b71427cbf343
Revises: 1dec4a61c089
Create Date: 2024-08-02 10:38:39.371868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71427cbf343'
down_revision = '1dec4a61c089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_destination_association', schema=None) as batch_op:
        batch_op.drop_index('ix_user_destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_destination_association', schema=None) as batch_op:
        batch_op.create_index('ix_user_destination', ['user_id', 'destination_id'], unique=False)

    # ### end Alembic commands ###
