"""add User Destination association table

Revision ID: d94914684480
Revises: 71f86b2f8517
Create Date: 2024-07-28 09:18:03.954743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94914684480'
down_revision = '71f86b2f8517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_destination_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_user_destination_association_destination_id_destinations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_destination_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'destination_id', name=op.f('pk_user_destination_association'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_destination_association')
    # ### end Alembic commands ###
