"""remove trip_id from actiity model

Revision ID: da102e2ad05e
Revises: b71427cbf343
Create Date: 2024-08-11 11:11:32.357018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da102e2ad05e'
down_revision = 'b71427cbf343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_trip_id_trips', type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_activities_trip_id_trips', 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###
