"""remove trip_id for activity model

Revision ID: e3d1966676c1
Revises: 5581765df422
Create Date: 2024-08-12 16:04:37.281842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d1966676c1'
down_revision = '5581765df422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_trip_id_trips', type_='foreignkey')
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_activities_trip_id_trips', 'trips', ['trip_id'], ['id'])

    # ### end Alembic commands ###
